matrix:
  include:
    - language: python
      python:
      - 3.6
      install:
      - pip install -r server/requirements.txt
      - pip install pylint
      script:
      - pylint server/manage.py
      - pylint server/server/
