matrix:
  include:
    - language: python
      python:
      - 3.6
      install:
      - pip install -r server/requirements.txt
      - pip install flake8
      script:
      - find -name "*.py" -not -path "./*/migrations/*" -not -path "./venv/*" | flake8
