version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      # Django settings
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DEBUG=${DEBUG}
      - TIME_ZONE=${TIME_ZONE}
      # Database settings
      - DATABASE_ENGINE=${DATABASE_ENGINE}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      # Running in docker settings
      - PORT=${PORT:-8000}
      # Other
      - SECRET_KEY=${SECRET_KEY}
      - USER_TOKEN_EXPIRING=${USER_TOKEN_EXPIRING}
    ports: 
      - ${PORT:-8000}:8080
